# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geekyclaw < Formula
  desc "Fast, lightweight local AI assistant with persistent memory and 89 LLM provider presets"
  homepage "https://github.com/LIT2451/GeekyClaw"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.3.2/geekyclaw_0.3.2_darwin_amd64.tar.gz"
      sha256 "9c0682bb25cd6b4743b177a8ca8133d599e701e22ec3567da81ce57ef741147a"

      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.3.2/geekyclaw_0.3.2_darwin_arm64.tar.gz"
      sha256 "b9443a42ac4b40b3c1ea4e3dc432e023502c43bc6cd1a4aa4798124acb598583"

      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.3.2/geekyclaw_0.3.2_linux_amd64.tar.gz"
      sha256 "c4be95666cbfb802739ed8ec36a61086782734663b0aed005a0d760cf95dfa61"
      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.3.2/geekyclaw_0.3.2_linux_arm64.tar.gz"
      sha256 "87d4dca93153d75a70d71608cd08e531e07ddcf3c2ebe88b3473c2a38b579caf"
      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
  end

  test do
    system bin/"geekyclaw", "version"
  end
end
