# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geekyclaw < Formula
  desc "Fast, lightweight local AI assistant with persistent memory and 89 LLM provider presets"
  homepage "https://github.com/LIT2451/GeekyClaw"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.2.2/geekyclaw_0.2.2_darwin_amd64.tar.gz"
      sha256 "b8b0ceca51f56cc8571bcc8e0df0b9486676c7fe2c6bcdbfa578b330c9c56fa0"

      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.2.2/geekyclaw_0.2.2_darwin_arm64.tar.gz"
      sha256 "b83aea8957fb4940184a423ebb6b216baa4acee67b184ccfa2bfd867cd2db8fb"

      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.2.2/geekyclaw_0.2.2_linux_amd64.tar.gz"
      sha256 "83587c8d5e7dbbedfe770967ff0884e99d00b68a0a4ff83e5832ccaccba1bea3"
      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LIT2451/GeekyClaw/releases/download/v0.2.2/geekyclaw_0.2.2_linux_arm64.tar.gz"
      sha256 "cdede05b83f6883651b96ec37255734651b578eeb6067618013a1dba03cb037d"
      define_method(:install) do
        bin.install "geekyclaw"
      end
    end
  end

  test do
    system bin/"geekyclaw", "version"
  end
end
